### ISSUE TITLE
Ports for docker compose?

### ISSUE THREAD

**Issue by kangruixiang** [oppiliappan/lurker#15]
Hi there:

I'm trying to run Lurker via docker compose but having trouble with setting the port:

```
version: "3.9"
services:
  lurker:
    image: ghcr.io/oppiliappan/lurker:latest
    container_name: Lurker
    security_opt:
      - no-new-privileges:true
    ports:
      - 9495:3000
    volumes:
      - /Users/fdsafsd/Documents/docker/lurker:/data
    restart: on-failure:5
```

With this I get "Connection was reset" error message. 

Thanks in advance.
